version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      semver-major-days: 20
      semver-minor-days: 10
      semver-patch-days: 5
