---
- name: Configure dev VM
  hosts: all
  gather_facts: true
  vars:
    logout_delay: 30
    shutdown_check_interval: 5

  tasks:
    # - name: Display all facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Create shutdown check script
      become: true
      ansible.builtin.copy:
        dest: /root/shutdown-check.sh
        mode: u+rx
        content: |
          #!/usr/bin/env bash
          if [ "$(w -h | sort --key=1,1 --unique | wc --lines)" -eq 0 ]; then
            wall "No users logged in for {{ logout_delay }} minutes, shutting down..."
            shutdown -P now
          fi

    - name: Shut machine down after idle
      become: true
      ansible.builtin.cron:
        name: Shutdown check
        minute: "*/{{ shutdown_check_interval }}"
        job: /root/shutdown-check.sh

    - name: Force user logout after inactivity
      become: true
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#?StopIdleSessionSec="
        line: StopIdleSessionSec={{ logout_delay }}min

    - name: Add Docker repository
      become: true
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
        suites: "{{ ansible_facts.distribution_release | lower }}"
        components: stable
        architectures: amd64
        signed_by: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg"
        state: present
        enabled: true

    - name: Upgrade all installed apt packages
      become: true
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        install_recommends: false
        update_cache: true
        upgrade: dist

    - name: Install tools via apt
      become: true
      ansible.builtin.apt:
        install_recommends: false
        update_cache: true
        state: present
        name:
          - bat
          - build-essential
          - command-not-found
          - containerd.io
          - curl
          - direnv
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - eza
          - fish
          - fzf
          - git
          - htop
          - hyperfine
          - libclang-dev
          - libnss3-dev
          - linux-perf
          - lld
          - net-tools
          - ninja-build
          - pkg-config
          - python-is-python3
          - python3-pip
          - ripgrep
          - sccache
          - starship
          - tmux
          - unzip
          - watchman
          - zoxide

    - name: Add user to Docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_facts.user_id }}"
        groups: docker
        append: true

    - name: Install or update tools via installer scripts
      vars:
        tools:
          - name: Claude Code
            bin: ~/.local/bin/claude
            url: https://claude.ai/install.sh
            install_args: ""
            update_cmd: ~/.local/bin/claude update
          - name: Rust
            bin: ~/.cargo/bin/cargo
            url: https://sh.rustup.rs
            install_args: -y --default-toolchain nightly --component rust-analyzer,miri,llvm-tools
            update_cmd: ~/.cargo/bin/rustup update
          - name: cargo-binstall
            bin: ~/.cargo/bin/cargo-binstall
            url: https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh
            install_args: ""
            update_cmd: ""
      block:
        - name: Check if tools are installed
          ansible.builtin.stat:
            path: "{{ item.bin }}"
          loop: "{{ tools }}"
          loop_control:
            label: "{{ item.name }}"
          register: tool_check

        - name: Download installer scripts
          ansible.builtin.get_url:
            url: "{{ item.item.url }}"
            dest: "/tmp/{{ item.item.name | lower | replace(' ', '-') }}-install.sh"
            mode: u+rx
          loop: "{{ tool_check.results }}"
          loop_control:
            label: "{{ item.item.name }}"
          when: not item.stat.exists

        - name: Install tools
          ansible.builtin.command: "/tmp/{{ item.item.name | lower | replace(' ', '-') }}-install.sh {{ item.item.install_args }}"
          args:
            creates: "{{ item.item.bin }}"
          loop: "{{ tool_check.results }}"
          loop_control:
            label: "{{ item.item.name }}"
          when: not item.stat.exists

        - name: Update tools
          ansible.builtin.command: "{{ item.item.update_cmd }}"
          register: tool_update
          changed_when: tool_update.rc != 0
          loop: "{{ tool_check.results }}"
          loop_control:
            label: "{{ item.item.name }}"
          when: item.stat.exists and item.item.update_cmd | length > 0

    - name: Install Rust tools
      ansible.builtin.command: ~/.cargo/bin/cargo-binstall --no-confirm --locked "{{ item.crate }}"
      args:
        creates: "~/.cargo/bin/{{ item.creates }}"
      loop:
        - { crate: cargo-audit, creates: cargo-audit }
        - { crate: cargo-deny, creates: cargo-deny }
        - { crate: cargo-fuzz, creates: cargo-fuzz }
        - { crate: cargo-hack, creates: cargo-hack }
        - { crate: cargo-llvm-cov, creates: cargo-llvm-cov }
        - { crate: cargo-machete, creates: cargo-machete }
        - { crate: cargo-mutants, creates: cargo-mutants }
        - { crate: cargo-nextest, creates: cargo-nextest }
        - { crate: cargo-show-asm, creates: cargo-asm }
        - { crate: cargo-update, creates: cargo-install-update }
        - { crate: cargo-vet, creates: cargo-vet }
        - { crate: cbindgen, creates: cbindgen }
        - { crate: critcmp, creates: critcmp }
        - { crate: samply, creates: samply }
        - { crate: wild-linker, creates: wild }
        - { crate: zizmor, creates: zizmor }

    - name: Update Rust tools
      ansible.builtin.command: ~/.cargo/bin/cargo install-update --all --git --locked
      register: cargo_update
      changed_when: cargo_update.rc != 0

    - name: Configure bash
      block:
        - name: Source ~/.bashrc.local
          ansible.builtin.lineinfile:
            path: ~/.bashrc
            regexp: "^source ~/.bashrc.local"
            line: "source ~/.bashrc.local"
        - name: Configure ~/.bashrc.local
          ansible.builtin.copy:
            src: files/bash
            dest: ~/.bashrc.local
            mode: u+r

    - name: Create config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: u+rwx
      loop:
        - ~/.config/bat
        - ~/.config/fish

    - name: Copy config files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u+r
      loop:
        - { src: files/bat, dest: ~/.config/bat/config }
        - { src: files/fish, dest: ~/.config/fish/config.fish }
        - { src: files/mozconfig, dest: ~/.mozconfig }
        - { src: files/ripgrep, dest: ~/.config/ripgrep }
        - { src: files/starship, dest: ~/.config/starship.toml }
