#!/usr/bin/env fish

# see https://github.com/tangledhelix/dotfiles/blob/master/tmux.conf

# Default termtype. If the rcfile sets $TERM, that overrides this value.
set -g default-terminal screen-256color

# Ring the bell if any background window rang a bell
set -g bell-action any

# Watch for activity in background windows
setw -g monitor-activity on

# scrollback size
set -g history-limit 10000

# pass through xterm keys
set -g xterm-keys on

# Redraw the client (if interrupted by wall, etc)
bind R refresh-client

set -g mouse on

# Re-tile on pane cose
set-hook -g after-kill-pane 'select-layout tiled'
set-hook -g pane-exited 'select-layout tiled'
